# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='create_by',
            field=models.CharField(default='', max_length=100, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishtask',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 21, 9, 56, 47, 294623, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='product',
            field=models.CharField(max_length=100, verbose_name='\u4ea7\u54c1\u7ebf'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='publish_time',
            field=models.DateTimeField(null=True, verbose_name='\u8ba1\u5212\u53d1\u7248\u65f6\u95f4'),
        ),
    ]
