# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0002_auto_20160721_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishtask',
            name='submit_time',
            field=models.DateTimeField(null=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4'),
        ),
    ]
