# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0003_auto_20160721_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='code_branch',
            field=models.CharField(default='', max_length=100, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
