# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0004_publishtask_code_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishtask',
            old_name='code_branch',
            new_name='code_tag',
        ),
    ]
