# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0005_auto_20160722_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='database_update',
            field=models.TextField(default='', verbose_name='\u6570\u636e\u5e93\u66f4\u65b0\u8bf4\u660e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishtask',
            name='sql_path',
            field=models.FileField(default='', upload_to=b'/sql/', verbose_name='\u66f4\u65b0SQL\u6587\u4ef6'),
            preserve_default=False,
        ),
    ]
