# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0006_auto_20160722_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishtask',
            name='sql_path',
        ),
        migrations.AddField(
            model_name='publishtask',
            name='update_sql',
            field=models.FileField(default='', upload_to=b'', verbose_name='\u66f4\u65b0SQL\u6587\u4ef6'),
            preserve_default=False,
        ),
    ]
