# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0007_auto_20160722_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishtask',
            name='code_dir',
            field=models.TextField(null=True, verbose_name='\u4ee3\u7801\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='code_tag',
            field=models.CharField(max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='database_update',
            field=models.TextField(null=True, verbose_name='\u6570\u636e\u5e93\u66f4\u65b0\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='product',
            field=models.CharField(max_length=100, null=True, verbose_name='\u4ea7\u54c1\u7ebf'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='settings',
            field=models.TextField(null=True, verbose_name='\u73af\u5883\u8bbe\u7f6e'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='submit_by',
            field=models.CharField(max_length=100, null=True, verbose_name='\u63d0\u4ea4\u4eba'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='update_note',
            field=models.TextField(null=True, verbose_name='\u66f4\u65b0\u8bf4\u660e'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='update_sql',
            field=models.CharField(max_length=1000, null=True, verbose_name='\u66f4\u65b0SQL\u6587\u4ef6'),
        ),
    ]
