# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0009_auto_20160722_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishtask',
            old_name='update_sql',
            new_name='upload_sql',
        ),
    ]
