# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0011_auto_20160725_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishtask',
            name='seq_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u53d1\u5e03\u5e8f\u5217\u53f7'),
        ),
    ]
