# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0012_auto_20160729_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='qa_note',
            field=models.TextField(null=True, verbose_name='\u6d4b\u8bd5\u8bc4\u4f30\u5efa\u8bae'),
        ),
    ]
