# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPublishTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.CharField(max_length=50, unique=True, verbose_name='\u53d1\u5e03\u5e8f\u5217\u53f7')),
                ('style', models.CharField(max_length=100, verbose_name='\u7c7b\u578b')),
                ('update_remark', models.TextField(verbose_name='\u66f4\u65b0\u7406\u7531')),
                ('client_apk_path', models.CharField(max_length=1000, null=True, verbose_name='APK')),
                ('client_sys_AndroidPublishVersion', models.CharField(max_length=100, null=True)),
                ('client_sys_IOSPublishVersion', models.CharField(max_length=100, null=True)),
                ('client_sys_isforcedupdate', models.CharField(max_length=1000, null=True)),
                ('client_config_iossjversion', models.CharField(max_length=100, null=True)),
                ('client_config_iosUpdateRemark', models.TextField(null=True)),
                ('client_config_androidversion', models.CharField(max_length=100, null=True)),
                ('client_config_androidsjversion', models.CharField(max_length=100, null=True)),
                ('client_config_downloadandroidpath', models.CharField(max_length=1000, null=True)),
                ('client_config_androidverremark', models.TextField(null=True)),
                ('client_config_androidsUpdateRemark', models.TextField(null=True)),
                ('courier_apk_path', models.CharField(max_length=1000, null=True)),
                ('courier_sys_AndroidPublishVersion', models.CharField(max_length=100, null=True)),
                ('courier_sys_IOSPublishVersion', models.CharField(max_length=100, null=True)),
                ('courier_sys_isforcedupdate', models.CharField(max_length=100, null=True)),
                ('courier_config_iossjversion', models.CharField(max_length=100, null=True)),
                ('courier_config_iosUpdateRemark', models.TextField(null=True)),
                ('courier_config_androidversion', models.CharField(max_length=100, null=True)),
                ('courier_config_androidsjversion', models.CharField(max_length=100, null=True)),
                ('courier_config_downloadandroidpath', models.CharField(max_length=1000, null=True)),
                ('courier_config_androidverremark', models.TextField(null=True)),
                ('courier_config_androidsUpdateRemark', models.TextField(null=True)),
                ('submit_time', models.DateTimeField(null=True, verbose_name='\u63d0\u4ea4\u65f6\u95f4')),
                ('submit_by', models.CharField(max_length=100, null=True, verbose_name='\u63d0\u4ea4\u4eba')),
                ('deploy_time', models.DateTimeField(null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('deploy_by', models.CharField(max_length=100, null=True, verbose_name='\u53d1\u5e03\u4eba')),
                ('status', models.CharField(max_length=100, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('create_by', models.CharField(max_length=100, verbose_name='\u521b\u5efa\u4eba')),
            ],
        ),
    ]
