# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexpress', '0002_apppublishtask_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppublishtask',
            name='platform',
            field=models.CharField(default='', max_length=100, verbose_name='\u5e73\u53f0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apppublishtask',
            name='version',
            field=models.CharField(max_length=100, verbose_name='\u7248\u672c\u53f7'),
        ),
    ]
