# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexpress', '0003_auto_20160803_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppublishtask',
            name='approval_by',
            field=models.CharField(max_length=100, null=True, verbose_name='\u5ba1\u6838\u4eba'),
        ),
        migrations.AddField(
            model_name='apppublishtask',
            name='approval_time',
            field=models.DateTimeField(null=True, verbose_name='\u5ba1\u6838\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='apppublishtask',
            name='publish_time',
            field=models.CharField(max_length=50, null=True, verbose_name='\u8ba1\u5212\u53d1\u7248\u65f6\u95f4'),
        ),
    ]
