# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appexpress', '0005_apppublishtask_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppublishtask',
            old_name='courier_sys_isforcedupdate',
            new_name='client_sys_Androidisforcedupdate',
        ),
        migrations.RemoveField(
            model_name='apppublishtask',
            name='client_sys_isforcedupdate',
        ),
        migrations.AddField(
            model_name='apppublishtask',
            name='client_sys_IOSisforcedupdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apppublishtask',
            name='courier_sys_Androidisforcedupdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apppublishtask',
            name='courier_sys_IOSisforcedupdate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
